In [2]:
import pandas as pd
import numpy as np
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
from funcoes.funcoes_exploratoria import *
from scipy import stats

In [3]:
# Importando o df
df_original = pd.read_csv('../raw/data_raw.csv')
df_original

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530.0,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310.0,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020.0,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600.0,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020.0,0,2008,0,98144,47.5941,-122.299,1020,1357

In [4]:
analise_dados(df_original)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,object,21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,float64,21611,946,2,0.01%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [6]:
# Confirmando os id repetidos - Para ter certeza
df_id = df_tratado[df_tratado.duplicated(subset=['id'], keep=False)] 
df_id.sort_values(by='id')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2496,1000102,2014-09-16,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
2497,1000102,2015-04-22,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
16814,7200179,2014-10-16,150000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
16815,7200179,2015-04-24,175000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
11433,109200390,2014-08-20,245000.0,3,1.75,1480,3900,1.0,0,0,...,7,1480.0,0,1980,0,98023,47.2977,-122.367,1830,6956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6345,9828200460,2014-06-27,260000.0,2,1.00,700,4800,1.0,0,0,...,7,700.0,0,1922,0,98122,47.6147,-122.300,1440,4800
15200,9834200305,2015-02-10,615000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
15199,9834200305,2014-07-16,350000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
1086,9834200885,2015-04-20,550000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080
1085,9834200885,2014-07-17,360000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080

In [7]:
# Visualizando e entendendo os nulos
df_nulos = df_tratado[df_tratado.isna().any(axis=1)]
df_nulos

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10,1736800520,2015-04-03,662500.0,3,2.5,3560,9796,1.0,0,0,...,8,NaN,1700,1965,0,98007,47.6007,-122.145,2210,8925
17,6865200140,2014-05-29,485000.0,4,1.0,1600,4300,1.5,0,0,...,7,NaN,0,1916,0,98103,47.6648,-122.343,1610,4300

In [16]:
# Ver se não se repete pelo id --> (Não deu)
display(df_tratado[df_tratado['id']==1736800520])
display(df_tratado[df_tratado['id']==6865200140])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10,1736800520,2015-04-03,662500.0,3,2.5,3560,9796,1.0,0,0,...,8,NaN,1700,1965,0,98007,47.6007,-122.145,2210,8925

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
17,6865200140,2014-05-29,485000.0,4,1.0,1600,4300,1.5,0,0,...,7,NaN,0,1916,0,98103,47.6648,-122.343,1610,4300

In [9]:
# Confirmando hipotese de area construida ser porão + geral
df_area = df_tratado[['sqft_living','sqft_above','sqft_basement']]
df_area['hipotese_soma'] = df_area['sqft_above'] + df_area['sqft_basement']
diferencas = df_area[df_area['hipotese_soma'] != df_area['sqft_living']]
diferencas

C:\Users\gio_m\AppData\Local\Temp\ipykernel_13184\919201466.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_area['hipotese_soma'] = df_area['sqft_above'] + df_area['sqft_basement']

    sqft_living  sqft_above  sqft_basement  hipotese_soma
10         3560         NaN           1700            NaN
17         1600         NaN              0            NaN

In [10]:
# Substituindo os nulos pelo calculo (living - basement)
df_semnulos = df_tratado.copy()
df_semnulos['sqft_above'] = df_semnulos['sqft_living'] - df_semnulos['sqft_basement']

In [11]:
# Conferindo tratamento inicial
analise_dados(df_semnulos)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,datetime64[ns],21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,int64,21613,946,0,0.0%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [12]:
# Salvando o Data Cleaning
df_semnulos.to_csv('../processed/df_clean.csv', index=False, sep=';', encoding='utf-8-sig')