In [21]:
import pandas as pd
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
from funcoes.funcoes_exploratoria import *

In [ ]:
df_original = pd.read_csv('../dados/data_raw.csv')
df_original

In [26]:
analise_dados(df_original)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,object,21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,float64,21611,946,2,0.01%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [27]:
# Correção do datetime
df_tratado = df_original.copy()
df_tratado['date'] = pd.to_datetime(df_tratado['date'])
df_tratado['date'].astype

<bound method NDFrame.astype of 0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]>

In [25]:
analise_dados(df_tratado)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,datetime64[ns],21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,float64,21611,946,2,0.01%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [34]:
# Confirmando os id repetidos
df_id = df_tratado[df_tratado.duplicated(subset=['id'], keep=False)] 
df_id.sort_values(by='id')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2496,1000102,2014-09-16,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
2497,1000102,2015-04-22,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
16814,7200179,2014-10-16,150000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
16815,7200179,2015-04-24,175000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
11433,109200390,2014-08-20,245000.0,3,1.75,1480,3900,1.0,0,0,...,7,1480.0,0,1980,0,98023,47.2977,-122.367,1830,6956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6345,9828200460,2014-06-27,260000.0,2,1.00,700,4800,1.0,0,0,...,7,700.0,0,1922,0,98122,47.6147,-122.300,1440,4800
15200,9834200305,2015-02-10,615000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
15199,9834200305,2014-07-16,350000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
1086,9834200885,2015-04-20,550000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080
1085,9834200885,2014-07-17,360000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080

In [43]:
# Visualizando nulos
df_nulos = df_tratado[df_tratado.isna().any(axis=1)]
df_nulos

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10,1736800520,2015-04-03,662500.0,3,2.5,3560,9796,1.0,0,0,...,8,NaN,1700,1965,0,98007,47.6007,-122.145,2210,8925
17,6865200140,2014-05-29,485000.0,4,1.0,1600,4300,1.5,0,0,...,7,NaN,0,1916,0,98103,47.6648,-122.343,1610,4300

In [ ]:
# Ver se não se repete pelo id --> (Não deu)
df_comparar = df_tratado[df_tratado['id']==6865200140]
df_comparar

In [ ]:
# Confirmando hipotese de area construida ser porão + geral
df_area = df_tratado[['sqft_living','sqft_above','sqft_basement']]
df_area['hipotese_soma'] = df_area['sqft_above'] + df_area['sqft_basement']
diferencas = df_area[df_area['hipotese_soma'] != df_area['sqft_living']]
diferencas

C:\Users\gio_m\AppData\Local\Temp\ipykernel_1688\1057162259.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_area['hipotese_soma'] = df_area['sqft_above'] + df_area['sqft_basement']

    sqft_living  sqft_above  sqft_basement  hipotese_soma
10         3560         NaN           1700            NaN
17         1600         NaN              0            NaN

In [61]:
# Retirando os nulos
df_semnulos = df_tratado.copy()
df_semnulos['sqft_above'] = df_semnulos['sqft_living'] - df_semnulos['sqft_basement'] 
df_tratado_final = df_semnulos[df_semnulos.isna().any(axis=1)]
df_tratado_final

Empty DataFrame
Columns: [id, date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15]
Index: []

[0 rows x 21 columns]

In [ ]:
# Conferindo tratamento inicial
analise_dados(df_semnulos)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,datetime64[ns],21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,int64,21613,946,0,0.0%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [64]:
resumo_estatistico(df_semnulos)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,...,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00
mean,4.580302e+09,2014-10-29 04:38:01.959931648,540088.14,3.37,2.11,2079.90,15106.97,1.49,0.01,0.23,...,7.66,1788.39,291.51,1971.01,84.40,98077.94,47.56,-122.21,1986.55,12768.46
min,1.000102e+06,2014-05-02 00:00:00,75000.00,0.00,0.00,290.00,520.00,1.00,0.00,0.00,...,1.00,290.00,0.00,1900.00,0.00,98001.00,47.16,-122.52,399.00,651.00
25%,2.123049e+09,2014-07-22 00:00:00,321950.00,3.00,1.75,1427.00,5040.00,1.00,0.00,0.00,...,7.00,1190.00,0.00,1951.00,0.00,98033.00,47.47,-122.33,1490.00,5100.00
50%,3.904930e+09,2014-10-16 00:00:00,450000.00,3.00,2.25,1910.00,7618.00,1.50,0.00,0.00,...,7.00,1560.00,0.00,1975.00,0.00,98065.00,47.57,-122.23,1840.00,7620.00
75%,7.308900e+09,2015-02-17 00:00:00,645000.00,4.00,2.50,2550.00,10688.00,2.00,0.00,0.00,...,8.00,2210.00,560.00,1997.00,0.00,98118.00,47.68,-122.12,2360.00,10083.00
max,9.900000e+09,2015-05-27 00:00:00,7700000.00,33.00,8.00,13540.00,1651359.00,3.50,1.00,4.00,...,13.00,9410.00,4820.00,2015.00,2015.00,98199.00,47.78,-121.32,6210.00,871200.00
std,2.876566e+09,-,367127.20,0.93,0.77,918.44,41420.51,0.54,0.09,0.77,...,1.18,828.09,442.58,29.37,401.68,53.51,0.14,0.14,685.39,27304.18

In [ ]:
# Visualizando as colunas com poucos elementos
colunas_filtradas = df_semnulos.nunique() < 50
df_poucos_valores = df_semnulos.loc[:, colunas_filtradas]

contagem_valores(df_poucos_valores)

In [78]:
df_novascolunas = df_semnulos.copy()
df_novascolunas['price_sqft_living'] = (df_novascolunas['price'] / df_novascolunas['sqft_living']).round(2)
df_novascolunas['price_sqft_lot'] = (df_novascolunas['price']/df_novascolunas['sqft_lot']).round(2)
df_novascolunas['price_sqft_above'] = (df_novascolunas['price_sqft_living']/df_novascolunas['sqft_above']).round(2)
df_novascolunas['price_sqft_basement'] = (df_novascolunas['price_sqft_living']/df_novascolunas['sqft_basement']).round(2)
df_novascolunas['age'] = 2026 - df_novascolunas['yr_built']
df_novascolunas['lot_15_compare'] =  df_novascolunas['sqft_lot']/df_novascolunas['sqft_lot15']
df_novascolunas['living_15_compare'] = df_novascolunas['sqft_living']/df_novascolunas['sqft_living15']
df_novascolunas['mean_price_zipcode'] = (df_novascolunas.groupby('zipcode')['price'].transform('mean')).round(2)

In [79]:
import numpy as np

df_novascolunas['age_renovated'] = np.where(
    df_novascolunas['yr_renovated'] == 0, 
    df_novascolunas['age'], 
    2026 - df_novascolunas['yr_renovated']
)

In [80]:
df_novascolunas

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_lot15,price_sqft_living,price_sqft_lot,price_sqft_above,price_sqft_basement,age,lot_15_compare,living_15_compare,mean_price_zipcode,age_renovated
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,5650,188.05,39.27,0.16,inf,71,1.000000,0.880597,310612.76,71
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,7639,209.34,74.29,0.10,0.52,75,0.948030,1.520710,469455.77,35
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,8062,233.77,18.00,0.30,inf,93,1.240387,0.283088,462480.04,93
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,5000,308.16,120.80,0.29,0.34,61,1.000000,1.441176,551688.67,61
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,7503,303.57,63.12,0.18,inf,39,1.076903,0.933333,685605.78,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0,0,...,1509,235.29,318.30,0.15,inf,17,0.749503,1.000000,584919.21,17
21609,6600060120,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0,0,...,7200,173.16,68.81,0.07,inf,12,0.807361,1.262295,359483.24,12
21610,1523300141,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0,0,...,2007,394.22,297.85,0.39,inf,17,0.672646,1.000000,594547.65,17
21611,291310100,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0,0,...,1287,250.00,167.50,0.16,inf,22,1.855478,1.134752,616990.59,22
21612,1523300157,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0,0,...,1357,318.63,302.04,0.31,inf,18,0.792926,1.000000,594547.65,18